default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: mapanda_development
   username: valdiearsanur
   password: valdiearsanur

test:
   adapter: postgresql
   encoding: unicode
   database: mapanda_test
   username: valdiearsanur
   password: valdiearsanur
 
production:
   adapter: postgresql
   encoding: unicode
   database: mapanda_production
   username: valdiearsanur
   password: valdiearsanur